<template>
<div class="container">
  <section class="content">
    <span class="input input--minoru">
					<input class="input__field input__field--minoru" type="text" id="input-13" />
					<label class="input__label input__label--minoru" for="input-13">
						<span class="input__label-content input__label-content--minoru">学工号</span>
					</label>
				</span>
    <span class="input input--minoru">
					<input class="input__field input__field--minoru" type="password" id="input-14" />
					<label class="input__label input__label--minoru" for="input-14">
						<span class="input__label-content input__label-content--minoru">密码</span>
					</label>
				</span>
    <span><button class="heartbeat" value="提交"/></span>
  </section>
</div>
</template>

<script>
export default {
  name: "usersheet"
}
</script>

<style scoped>
@import ".././assets/css/component.css";
@import ".././assets/css/normalize.css";
@import ".././assets/css/demo.css";

.heartbeat {
  animation: heartbeat 1.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-7-3 18:10:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@keyframes heartbeat {
  from {
    transform: scale(1);
    transform-origin: center center;
    animation-timing-function: ease-out;
  }
  10% {
    transform: scale(0.91);
    animation-timing-function: ease-in;
  }
  17% {
    transform: scale(0.98);
    animation-timing-function: ease-out;
  }
  33% {
    transform: scale(0.87);
    animation-timing-function: ease-in;
  }
  45% {
    transform: scale(1);
    animation-timing-function: ease-out;
  }
}

</style>